import { veados } from '@prisma/client'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useRef } from 'react'
import Table360 from '../../components/Tabela360'
import styles from '../../styles/Home.module.css'

export const getStaticProps = async () => {
  const veados = await fetch(`${process.env.BASE_URL}/api/veados`).then(r => r.json())

  return { props : { veados }};
}

const Home: NextPage<{veados: veados[]}> = ({veados}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
        <div>
          <h1>VEADOS</h1>
        </div>
        <div>
          <Table360 posts={veados}></Table360>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
